### ISSUE TITLE
バージョン候補が二重に出力される場合がある

### ISSUE THREAD

**Issue by crow-misia** [gahojin/refresh-versions-plugin#22]
以下のバージョンカタログ時に、候補のバージョンが二重に出力される

librariesとplugins両方で参照している場合に発生していると思われる

libs.versions.toml
```toml
[versions]

google-dagger = "2.56"
##            ^ "2.56.1"
##            ^ "2.56.1"

[libraries]

google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-dagger" }

google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-dagger" }

[plugins]

google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }

```

settings.gradle.kts
```kotlin
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}
```
